apiVersion: v1
kind: Namespace
metadata:
  name: chuck
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chuck-operator
  namespace: chuck
  labels:
    control-plane: chuck-operator
spec:
  selector:
    matchLabels:
      control-plane: chuck-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: chuck-operator
    spec:

      containers:
        - name: manager
          imagePullPolicy: "Always"
          args:
            - "--enable-leader-election"
            - "--leader-election-id=chuck-operator"
            - "--leader-election-namespace=chuck"
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: controller:latest
      terminationGracePeriodSeconds: 10
