apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{pg.svc_name}}"
  namespace: "{{ ansible_operator_meta.namespace }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{pg.storage_size}}"
