apiVersion: v1
kind: Secret
metadata:
  name: env-secrets
  namespace: "{{ ansible_operator_meta.namespace }}"
data:
  POSTGRES_DB: {{ pg.dbname | b64encode }}
  POSTGRES_PASSWORD: {{ pg.pass | b64encode }}
  POSTGRES_USER: {{ pg.user | b64encode }}
  POSTGRES_HOST: {{ pg.svc_name | b64encode }}
