apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: "{{api.svc_name}}"
  namespace: "{{ansible_operator_meta.namespace}}"
spec:
  rules:
    - host: "{{(api.svc_name + '.' + cluster_domain).split(':')[0] }}"
      http:
        paths:
          - path: /
            backend:
              serviceName: "{{api.svc_name}}"
              servicePort: {{api.port}}