apiVersion: v1
kind: Service
metadata:
  name: "{{api.svc_name}}"
  namespace: "{{ ansible_operator_meta.namespace }}"
spec:
  selector:
    app: "{{api.svc_name}}"
  ports:
  - name: http
    port: {{api.port}}